okke:
  outputs:
    prod:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: cfm-reporting-database-prod.database.windows.net
      port: 1433
      database: cfm-dwh
      schema: Ikaros_Schema
      user: Ikaros_User
      password: # add user password here 
      trust_cert: true
      login_timeout: 15
  
  target: prod
